# Generated by Django 3.1.1 on 2020-09-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.IntegerField(max_length=10)),
                ('employee_name', models.CharField(max_length=150)),
                ('employee_age', models.IntegerField(max_length=5)),
                ('employee_sex', models.BinaryField()),
            ],
        ),
    ]
