# Generated by Django 3.1.1 on 2020-09-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_sex',
            field=models.BooleanField(),
        ),
    ]
