# Generated by Django 3.1.1 on 2020-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.URLField(primary_key=True, serialize=False)),
                ('product_code', models.IntegerField(unique=True)),
                ('product_name', models.CharField(max_length=150)),
                ('product_price', models.CharField(max_length=20)),
                ('product_desciption', models.CharField(max_length=150)),
            ],
        ),
    ]
