# Generated by Django 3.1.1 on 2020-09-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_shop', '0003_auto_20200926_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desciption',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
