# Generated by Django 3.1.1 on 2020-09-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_shop', '0004_auto_20200926_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
